# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2bdd28c524e9b4240be71c125e635a0fbdd29bc193ef1a6e8f572204d1813dc77ea80f9c99b8667b913daa457c7df6e188b29e3de8c9cf3a89c259d16287f8b

test:
  secret_key_base: f6cf180deda8db2a7f4956cb8ad1e489ce1334ff493695e1b2397d967c2847d6ad22ee6e2ee1d8d5f5f9b521774d7df43b00b6aa997024762f7c250c5896a523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
